FROM postgres:16

# Install dependencies and pgvector
RUN apt-get update && \
    apt-get install -y postgresql-server-dev-16 build-essential git && \
    git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && make install && \
    cd .. && rm -rf pgvector && \
    apt-get remove -y build-essential git && \
    apt-get autoremove -y && \
    apt-get clean

COPY backup.tar.gz /docker-entrypoint-initdb.d/backup.tar.gz
COPY init.sh /docker-entrypoint-initdb.d/init.sh

RUN chmod +x /docker-entrypoint-initdb.d/init.sh